### ISSUE TITLE
ImportError: cannot import name 'auroc_aupr_f1max' from 'adeval.cuda_mem_effic'

### ISSUE THREAD

**Issue by Nothingtolose9979** [guojiajeremy/Dinomaly#1]
utils.py line 24 
```from adeval.cuda_mem_effic import auroc_aupr_f1max as auroc_aupr_f1max_cuda```

ImportError: cannot import name 'auroc_aupr_f1max' from 'adeval.cuda_mem_effic' (/home/y9902/anaconda3/envs/anomalib_env/lib/python3.10/site-packages/adeval/cuda_mem_effic.py)

Could you please tell me what version of ```adeval``` is being used, and also, is there any additional implementation of these functions (```auroc_aupr_f1max```, ```auroc_aupr_f1max_aupro```, ```aupro```) somewhere?

**Comment by guojiajeremy** [comment]
adeval is not used. Just delete them. I commit a new utils.py with them deleted.

**Comment by Nothingtolose9979** [comment]
It worked! Thanks!
