### ISSUE TITLE
about multi-class detection score

### ISSUE THREAD

**Issue by xgzng** [guojiajeremy/Dinomaly#12]
Hello, the result of running your code is the average of detecting each category separately. Will the scores of directly detecting all categories be different？

**Comment by guojiajeremy** [comment]
You raised a very keen question. The answer is NO. The average AUC of N classes does not equal to the AUC of all images of N classes mixed. However, all previous multi-class UAD methods implemented the former class-separate inference setting.

Actually, we have a another paper discussing it: https://arxiv.org/abs/2404.00724
