### ISSUE TITLE
dropout rate问题

### ISSUE THREAD

**Issue by luowei-opg** [guojiajeremy/Dinomaly#7]
![drop](https://github.com/user-attachments/assets/a4ac06f3-5dd5-4c61-920d-ed6d87849e5b)
您好，我想请问在这个实验中，noiseless的设置是仅仅将dropout rate设置为0嘛，其他的LL,LC,LA模块是否被删除？，因为我仅仅将dropout rate设置为0后，得到的指标和表中不太一致，指标如下：
 I-Auroc:0.9926, I-AP:0.9954, I-F1:0.9860, P-AUROC:0.9757, P-AP:0.6294, P-F1:0.6427, P-AUPRO:0.9341

**Comment by guojiajeremy** [comment]
我double check了一下，I-AUROC是99.19，制表的时候写错了，其他指标没有问题。谢谢勘误。

**Comment by guojiajeremy** [comment]
LL,LC,LA模块没有删除

**Comment by luowei-opg** [comment]
好的 谢谢！
